"""Daily vehicle-expense generator: the "expense system" source of the batch layer.

Writes one CSV per business date:

    <LANDING_DIR>/expenses/<business_date>/vehicle_expenses.csv   (columns: EXPENSE_FIELDS)

Usage:
    python -m fleet.batch.generator --business-date 2026-01-01          # one date
    python -m fleet.batch.generator --follow                            # daemon (compose)
    python -m fleet.batch.generator --business-date 2099-01-05 --corrupt  # failure demo

Cost model per vehicle-day (profiles: fleet/common/fleet_profiles.py):

    distance_km  = (40 + 220 x demand_factor) x U(0.85, 1.15)
                   -> ~260 km for a normal taxi, ~105 km for a low-utilisation one;
                   on a service day the car spends part of the day in the workshop (x 0.6)
    fuel_cost    = distance / fuel_km_per_litre x FUEL_PRICE_PER_LITRE x U(0.95, 1.08)
                   (the noise is traffic / driving style)
    maintenance  = U(500, 1,100) x maintenance_factor                routine (tyres, cleaning)
                   + U(8,000, 19,000) if service_flag                workshop visit
    service_flag = random() < service_probability

All money is LKR (fuel at ~LKR 325/litre). With stream earnings of ~LKR 10,000-16,000
(normal) and ~3,000-6,000 (low utilisation) this gives a mix: normal -> mostly
profitable, low utilisation -> watch, high cost (6.5 km/l, ~LKR 13,000+ fuel) ->
unprofitable, maintenance heavy -> watch, and
unprofitable on its frequent service days. See the Batch section of the report.

Determinism: every vehicle-day has its own RNG seeded with
"<SIM_RANDOM_SEED>:<date>:<vehicle>", so a file can be regenerated byte-for-byte and
does not depend on the fleet size or on the order in which dates are generated.
"""

from __future__ import annotations

import argparse
import csv
import io
import os
import random
import sys
import tempfile
import time
from datetime import date
from pathlib import Path

from fleet.batch.validation import ExpenseValidationError, validate_rows
from fleet.common.config import Settings, load_settings
from fleet.common.contracts import EXPENSE_FIELDS, expense_file_path, vehicle_id
from fleet.common.fleet_profiles import FUEL_PRICE_PER_LITRE, profile_for
from fleet.common.logs import get_logger

log = get_logger("expense-generator")

# ---------------------------------------------------------------------------
# Tuning constants (see module docstring)
# ---------------------------------------------------------------------------
BASE_DISTANCE_KM = 40.0  # driven even without passengers (home, repositioning)
DEMAND_DISTANCE_KM = 220.0  # extra km at demand_factor 1.0
DISTANCE_NOISE = (0.85, 1.15)
SERVICE_DAY_DISTANCE_SHARE = 0.6
FUEL_NOISE = (0.95, 1.08)
ROUTINE_MAINTENANCE = (500.0, 1_100.0)  # LKR
SERVICE_COST = (8_000.0, 19_000.0)  # LKR, a workshop visit


def expense_row(business_date: date, vid: str, seed: int) -> dict[str, str]:
    """One vehicle-day of expenses, as the CSV strings that will be written."""
    profile = profile_for(vid)
    rng = random.Random(f"{seed}:{business_date.isoformat()}:{vid}")

    service = rng.random() < profile.service_probability
    distance = (BASE_DISTANCE_KM + DEMAND_DISTANCE_KM * profile.demand_factor) * rng.uniform(
        *DISTANCE_NOISE
    )
    if service:
        distance *= SERVICE_DAY_DISTANCE_SHARE
    fuel = distance / profile.fuel_km_per_litre * FUEL_PRICE_PER_LITRE * rng.uniform(*FUEL_NOISE)
    maintenance = rng.uniform(*ROUTINE_MAINTENANCE) * profile.maintenance_factor
    if service:
        maintenance += rng.uniform(*SERVICE_COST)

    return {
        "vehicle_id": vid,
        "fuel_cost": f"{fuel:.2f}",
        "maintenance_cost": f"{maintenance:.2f}",
        "distance_covered": f"{distance:.2f}",
        "service_flag": "true" if service else "false",
        "business_date": business_date.isoformat(),
    }


def generate_expenses(business_date: date, fleet_size: int, seed: int) -> list[dict[str, str]]:
    """Expense rows for vehicles V001..V<fleet_size> on one business date."""
    return [expense_row(business_date, vehicle_id(n), seed) for n in range(1, fleet_size + 1)]


def corrupt_expenses(business_date: date, fleet_size: int, seed: int) -> list[dict[str, str]]:
    """A deliberately INVALID file (failure-path demo): several rules broken at once."""
    rows = generate_expenses(business_date, fleet_size, seed)
    rows[0]["fuel_cost"] = "-125.50"  # negative_value
    rows[1]["vehicle_id"] = "BUS-17"  # invalid_vehicle_id
    rows[2]["maintenance_cost"] = ""  # missing_value
    rows[3]["service_flag"] = "maybe"  # invalid_service_flag
    rows[4]["business_date"] = "2001-02-30"  # invalid_business_date
    rows[5]["distance_covered"] = "lots"  # invalid_number
    rows.append(dict(rows[6]))  # duplicate_vehicle_id
    return rows


def to_csv(rows: list[dict[str, str]]) -> str:
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=EXPENSE_FIELDS, lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    return buf.getvalue()


def write_atomically(path: Path, content: str) -> None:
    """Write to a temp file in the same directory, then rename.

    rename() is atomic on one filesystem, so the Airflow sensor never sees a
    half-written file.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".tmp-", suffix=".csv")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        os.chmod(tmp, 0o644)
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


def generate_file(
    settings: Settings, business_date: date, corrupt: bool = False, overwrite: bool = True
) -> Path | None:
    """Generate, validate and write the expense file of one date. Returns its path.

    A normal file is validated BEFORE it is written (a generator bug must never produce
    a bad file). A --corrupt file is written without validation on purpose.
    """
    path = Path(expense_file_path(settings.landing_dir, business_date.isoformat()))
    if path.exists() and not overwrite:
        return None
    if corrupt:
        rows = corrupt_expenses(business_date, settings.fleet_size, settings.sim_random_seed)
    else:
        rows = generate_expenses(business_date, settings.fleet_size, settings.sim_random_seed)
    content = to_csv(rows)
    if not corrupt:
        result = validate_rows(content.splitlines(), business_date.isoformat(), str(path))
        if not result.is_valid:
            raise ExpenseValidationError(result)
    write_atomically(path, content)

    services = sum(r["service_flag"] == "true" for r in rows)
    log.info(
        "expense file written",
        extra={
            "fields": {
                "business_date": business_date.isoformat(),
                "path": str(path),
                "rows": len(rows),
                "corrupt": corrupt,
                "service_days": services,
                "total_fuel_cost": round(sum(_num(r["fuel_cost"]) for r in rows), 2),
                "total_maintenance_cost": round(sum(_num(r["maintenance_cost"]) for r in rows), 2),
            }
        },
    )
    return path


def _num(value: str) -> float:
    try:
        return float(value)
    except ValueError:
        return 0.0


# ---------------------------------------------------------------------------
# --follow: generate files for business dates the stream has finished
# ---------------------------------------------------------------------------
def follow(settings: Settings) -> None:
    """Poll PostgreSQL forever; write a file for every completed date without one."""
    from fleet.batch.dates import completed_business_dates
    from fleet.common.db import connect

    log.info(
        "follow mode started",
        extra={
            "fields": {
                "landing_dir": settings.landing_dir,
                "poll_seconds": settings.expense_poll_seconds,
                "fleet_size": settings.fleet_size,
            }
        },
    )
    while True:
        try:
            with connect(settings) as conn:
                completed = completed_business_dates(conn)
            missing = [
                d
                for d in completed
                if not Path(expense_file_path(settings.landing_dir, d.isoformat())).exists()
            ]
            for d in missing:
                generate_file(settings, d, overwrite=False)
            log.debug(
                "poll done",
                extra={"fields": {"completed_dates": len(completed), "generated": len(missing)}},
            )
        except Exception:
            # PostgreSQL restarting etc.: log and try again on the next poll
            log.exception("poll failed; retrying")
        time.sleep(settings.expense_poll_seconds)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate daily vehicle expense files")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--business-date", type=date.fromisoformat, help="YYYY-MM-DD")
    group.add_argument("--follow", action="store_true", help="generate completed dates forever")
    parser.add_argument(
        "--corrupt", action="store_true", help="write a deliberately invalid file (demo)"
    )
    args = parser.parse_args(argv)
    settings = load_settings()

    if args.follow:
        follow(settings)
        return 0
    try:
        generate_file(settings, args.business_date, corrupt=args.corrupt)
    except ExpenseValidationError as exc:
        log.error("generated data failed validation", extra={"fields": {"error": str(exc)}})
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
